spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orbis
    username: DBusername
    password: DBpass
    pool-size: 30
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    show-sql: true