server:
  port: 21420
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orbis
    username: s311734
    password: gul991
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#    show-sql: true
  security:
    ignored:
      - "*.bundle.*"
    user:
      password: pass